KABE Food Ordering System/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KABE_Food_Ordering_System.Logic;
using KABE_Food_Ordering_System.Models;
using KABE_Food_Ordering_System.ViewModels;

namespace KABE_Food_Ordering_System.Controllers
{
    public class FoodController : Controller
    {
        public FoodLogic foodLogic = new FoodLogic();
        public BaseLogic<Food> baseLogic = new BaseLogic<Food>(new ApplicationDbContext());
        public BaseLogic<Restaurant> restaurantLogic = new BaseLogic<Restaurant>(new ApplicationDbContext());


        
        // GET: Food
        [RestaurantRestrictLogic]
        public ActionResult Index()
        {
            RestaurantLogic resLogic = new RestaurantLogic();
            int id = Convert.ToInt32(Session["id"]);

            try
            {
                ApplicationDbContext _context = new ApplicationDbContext();

                //get all food
                var food = resLogic.GetAllRestaurantFoodsList(id);
                if (food != null)
                {
                    ViewBag.Results = food;
                    ViewBag.TotalItems = food.Count();

                    //    //get all price
                    //    var getPrice = resLogic.GetAllRestaurantFoodPrices(id);
                    //    ViewBag.Price = getPrice;
                    //}
                    return View(food);
                }
                //var getFood = new List<string>();
                //var findFood = new Food();
                //if (Food != null)
                //{
                //    foreach (var item in Food)
                //    {
                //        if (item != 0)
                //        {
                //            findFood = baseLogic.Get(item);
                //            getFood.Add(findFood.Name);
                //        }

                //    }
                else
                {
                    ViewBag.Results = null;
                    ViewBag.TotalItems = 0;

                    //    //get all price
                    //    var getPrice = resLogic.GetAllRestaurantFoodPrices(id);
                    //    ViewBag.Price = getPrice;
                    //}
                    return View(new List<Food>());
                }
                    
            }
            catch (Exception)
            {
                //ErrorLogger.Log("Message= " + ex.Message + "\nInner Exception= " + ex.InnerException + "\n");
                return PartialView("Error");
            }
            //return View();
        }

        

        // GET: Food/Add ---Returns the Location view page
        [RestaurantRestrictLogic]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(/*[Bind(Include = "Name")]*/ HttpPostedFileBase postedFile, Food model)
        {
            var price = Request.Form["price"];
            byte[] bytes;
            using (BinaryReader br = new BinaryReader(postedFile.InputStream))
            {
                bytes = br.ReadBytes(postedFile.ContentLength);
            }
            var restLogic = new RestaurantLogic();
            model.ContentType = postedFile.ContentType;
            model.Image = Convert.ToBase64String(bytes);
            var Id = Convert.ToInt32(Session["Id"]);
            Restaurant restaurant = new RestaurantLogic().GetByUserID(Id);
            ApplicationDbContext _context = new ApplicationDbContext();
            //if (restaurant != null)
            //{
            //    model.Restaurants.Add(restaurant.Id, price);
            //}
            int id = Convert.ToInt32(Session["id"]);

            var Food = restLogic.GetAllRestaurantFoods(id);
            var IsExist = false;
            
             try
            {
                if (foodLogic.IsDetailsExist(model.Name) /*&& foodLogic.IsRestaurantExist(model.Restaurants, Id)*/)
                {
                    //baseLogic.Save(model);
                    foodLogic.Save(model);
                    Food getFood = new FoodLogic().FindByName(model.Name);
                    var food = restaurant.FoodId;
                    var prices = restaurant.Price;
                    if (food == null)
                    {
                        food = "";
                        restaurant.FoodId = Convert.ToString(getFood.Id) + "," + Convert.ToString(price);

                    }
                    else
                    {
                        restaurant.FoodId = food + "," + Convert.ToString(getFood.Id) + "," + Convert.ToString(price);
                        //restaurant.FoodId = food + "," + Convert.ToString(getFood.Id);
                    }
                    if (prices == null)
                    {
                        prices = "";
                        restaurant.Price = Convert.ToString(price);

                    }
                    else
                    {
                        restaurant.Price = prices + "," + Convert.ToString(price);

                    }
                    //restaurant.FoodId = food + "," + Convert.ToString(getFood.Id);
                    //restaurant.Price = prices + "," + Convert.ToString(price);

                    //restaurant.Foods.Add(Convert.ToString(getFood.Id), price);
                    restaurantLogic.Update(restaurant);

                    ViewBag.Message = "Success";


                    return RedirectToAction("Index");

                }
                else
                {
                    Food getFood = new FoodLogic().FindByName(model.Name);
                    if (Food != null)
                    {
                        foreach (var item in Food)
                        {
                            if (item == getFood.Id)
                            {
                                IsExist = true;
                            }

                        }
                    }
                    if (IsExist == true)
                    {
                        ViewBag.Message = "Exist";
                        return View();
                    }
                    else
                    {
                        var food = restaurant.FoodId;
                        var prices = restaurant.Price;
                        if (food == null)
                        {
                            food = "";
                            restaurant.FoodId = Convert.ToString(getFood.Id);

                        }
                        else
                        {
                            restaurant.FoodId = food + "," + Convert.ToString(getFood.Id);
                        }
                        if (prices == null)
                        {
                            prices = "";
                            restaurant.Price = Convert.ToString(price);

                        }
                        else
                        {
                            restaurant.Price = prices + "," + Convert.ToString(price);

                        }
                        //restaurant.FoodId = food + "," + Convert.ToString(getFood.Id);
                        //restaurant.Price = prices + "," + Convert.ToString(price);
                        restaurantLogic.Update(restaurant);

                        ViewBag.Message = "Success";


                        return RedirectToAction("Index");

                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.ToString());
                return View(model);
            }
        }




    }
}

KABE Food Ordering System/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using KABE_Food_Ordering_System.Logic;
using KABE_Food_Ordering_System.Models;
using KABE_Food_Ordering_System.ViewModels;
//using CMS.DataEngine;

//using Kentico.Search;

namespace KABE_Food_Ordering_System.Controllers
{
    public class OrderController : Controller
    {
        FoodLogic food = new FoodLogic();
        LocationLogic location = new LocationLogic();
        RestaurantLogic restaurant = new RestaurantLogic();

        public BaseLogic<Food> foodLogic = new BaseLogic<Food>(new ApplicationDbContext());
        public BaseLogic<Order> orderLogic = new BaseLogic<Order>(new ApplicationDbContext());
        public BaseLogic<Restaurant> restaurantLogic = new BaseLogic<Restaurant>(new ApplicationDbContext());
        public BaseLogic<Location> locationLogic = new BaseLogic<Location>(new ApplicationDbContext());

        [CustomerRestrictLogic]
        [HttpGet]
        public ActionResult Pay(int id)
        {
            Order order = new OrderLogic().Get(id);
            FoodViewModels foodViewModels = new FoodViewModels();
            var findFood = new Food();
            var restaurant = new Restaurant();
            if (order.Status == OrderStatus.NotPaid)
            {
                findFood = new FoodLogic().Get(order.FoodId);
                restaurant = new RestaurantLogic().GetByUserID(order.RestaurantId);
                foodViewModels.Id = order.FoodId;

                foodViewModels.Name = findFood.Name;
                foodViewModels.RestaurantName = restaurant.Name;
                foodViewModels.ContentType = findFood.ContentType;
                foodViewModels.Image = findFood.Image;
                if (order.FoodQuantity > 0)
                {
                    foodViewModels.Price = Convert.ToDecimal(order.Amount) / Convert.ToInt32(order.FoodQuantity);
                }
                else
                {
                    foodViewModels.Price = Convert.ToDecimal(order.Amount) / 1;
                }
                var location = new LocationLogic().Get(restaurant.LocationId);
                foodViewModels.Location = location.Name;
                foodViewModels.About = restaurant.About;
                ViewBag.Data = foodViewModels;
                ViewBag.Msg = 1;
                ViewBag.VefriCode = order.VerificationCode;
                order.Locations = new LocationLogic().GetAll();
                return View(order);
            }
            else
            {
                return RedirectToAction("All");
            }

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomerRestrictLogic]
        public ActionResult Pay(Order getorder)
        {
            Order order = new OrderLogic().Get(getorder.Id);
            order.Locations = locationLogic.GetAll();
            order.ResidentialAddress = getorder.ResidentialAddress;
            order.Amount = getorder.Amount;
            order.FoodQuantity = getorder.FoodQuantity;
            order.LocationId = getorder.LocationId;
            if (order.Amount != "0")
            {
                //order.CardNumber = "00";
                //order.DeliveryDateTime = DateTime.Now;
                //order.OrderDateTime = DateTime.Now;
                //order.Status = OrderStatus.NotPaid;
                //order.VerificationCode = GenerateVerfCode();
                var email = Session["email"].ToString();
                var name = Session["username"].ToString();
                new AccountLogic().SendingVerificationCode(email, name, order.VerificationCode);
                //var rest = new RestaurantLogic().GetByUserID(order.RestaurantId);
                //order.RestaurantId = rest.RestaurantsId;
                //orderLogic.Update(order);
                //var price = Convert.ToInt32(order.Amount) / Convert.ToInt32(order.FoodQuantity);
                Session["OrderId"] = order.Id;
                Session["NewOrderId"] = order.Id;
                ViewBag.Amount = order.Amount;
                ViewBag.VefriCode = order.VerificationCode;
                //return View("Payment");
                ViewBag.Msg = 2;
                return View(order);
            }
            else
            {
                return View(order);
            }
            //else
            //{
            //    ViewBag.NoAmount = true;
            //    return Redirect("http://localhost:50125/Order/New?foodId=" + order.FoodId + "&restaurant=" + rest.Name + "&price=" + price);
            //}
        }
        [CustomerRestrictLogic]
        [HttpGet]
        public ActionResult New(int foodId, string restaurant, decimal price)
        {
            FoodViewModels foodViewModels = new FoodViewModels();
            foodViewModels.Id = foodId;
            var findFood = new FoodLogic().Get(foodId);
            Order order = new Order();
            order.Locations = locationLogic.GetAll();
            if (findFood != null)
            {
                foodViewModels.Name = findFood.Name;
                foodViewModels.RestaurantName = restaurant;
                foodViewModels.ContentType = findFood.ContentType;
                foodViewModels.Image = findFood.Image;
                foodViewModels.Price = price;
                ViewBag.Data = foodViewModels;
                order.CustomerId = Convert.ToInt32(Session["id"]);
                order.FoodId = foodId;
                //order.VerificationCode = GenerateVerfCode();
                order.VerificationCode = "000000";
                ViewBag.VefriCode = order.VerificationCode;
                order.Amount = Convert.ToString(price);
                order.RestaurantId = new RestaurantLogic().FindByName(foodViewModels.RestaurantName).Id;
                order.TransactionReference = generateGuid();
                ViewBag.Msg = 1;
            }

            return View(order);
        }

        
        //POST: Order/New
        [HttpPost]
        [CustomerRestrictLogic]
        public ActionResult New(Order order)
        {
            order.Locations = locationLogic.GetAll();

            if (order.Amount != "0")
            {
                order.CardNumber = "00";
                order.DeliveryDateTime = DateTime.Now;
                order.OrderDateTime = DateTime.Now;
                order.Status = OrderStatus.NotPaid;
                var email = Session["email"].ToString();
                var name = Session["username"].ToString();
                new AccountLogic().SendingVerificationCode(email, name, order.VerificationCode);
                var rest = new RestaurantLogic().Get(order.RestaurantId);
                order.RestaurantId = rest.RestaurantsId;
                orderLogic.Save(order);
                var price = Convert.ToInt32(order.Amount) / Convert.ToInt32(order.FoodQuantity);
                Session["OrderId"] = order.Id;
                Session["NewOrderId"] = order.Id;
                ViewBag.Amount = order.Amount;
                ViewBag.VefriCode = order.VerificationCode;
                ViewBag.Msg = 2;
                return View(order);
            }
            else
            {
                return View(order);
            }
            //else
            //{
            //    ViewBag.NoAmount = true;
            //    return Redirect("http://localhost:50125/Order/New?foodId=" + order.FoodId + "&restaurant=" + rest.Name + "&price=" + price);
            //}
        }
        [CustomerRestrictLogic]
        public ViewResult Search(string searchTerm)
        {
            if (searchTerm != "" && searchTerm != null)
            {
                var Food = new RestaurantLogic().GetListRestaurantFoods(searchTerm);
                int i = 0;
                var getRestaurant = new List<FoodViewModels>();
                var getLocation = new List<FoodViewModels>();
                var getFood = new List<FoodViewModels>();
                if (Food.Count() == 0)
                {
                    var restaurant = new RestaurantLogic().GetFoodsByRestaurant(searchTerm);

                    if (restaurant.Count != 0)
                    {
                        //var getPrice = new RestaurantLogic().GetListRestaurantFoodsPrice(searchTerm).ToArray();

                        ViewBag.Results = getRestaurant;
                        ViewBag.TotalItems = getRestaurant.Count();
                    }
                    else
                    {
                        var Location = new RestaurantLogic().GetFoodsByLocation(searchTerm);
                        if (Location.Count != 0)
                        {
                            //var getPrice = new RestaurantLogic().GetListRestaurantFoodsPrice(searchTerm).ToArray();
                            ViewBag.Results = getLocation;
                            ViewBag.TotalItems = getLocation.Count();
                        }
                        else
                        {

                            ViewBag.Results = null;
                            ViewBag.TotalItems = 0;

                        }
                    }
                }
                else
                {
                    //var getPrice = new RestaurantLogic().GetListRestaurantFoodsPrice(searchTerm).ToArray();

                    getFood = new RestaurantLogic().GetListRestaurantFoods(searchTerm);
                    ViewBag.Results = getFood;
                    ViewBag.TotalItems = getFood.Count();

                }

            }
            else
            {
                var getAll = new RestaurantLogic().GetAllRestaurantFoodsList();
                var getAllFoods = new List<FoodViewModels>();

                ViewBag.Results = getAll;
                ViewBag.TotalItems = getAll.Count();

            }

            return View();
        }
       

        [HttpPost]
        [OrderProcessing]
        [CustomerRestrictLogic]
        //[ValidateAntiForgeryToken]

KABE Food Ordering System/Views/Food/Add.cshtml
@model KABE_Food_Ordering_System.Models.Food
@{
    ViewBag.Title = "Add Food";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Add", "Food", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
<div class="col-md-6">
    @if (ViewBag.Message != null)
    {
        if (ViewBag.Message == "Success")
        {
            <div class="alert alert-success">
                <p>@ViewBag.Message <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> </p>

            </div>

        }
        else if (ViewBag.Message == "Exist")
        {
            <div class="alert alert-error">
                <p>Food Already Exist <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> </p>

            </div>

        }
        else if (ViewBag.Message == "Error")
        {
            <div class="alert alert-error">
                <p>@ViewBag.Message <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> </p>

            </div>

        }
    }

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group ">
        @Html.LabelFor(m => m.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", maxlength = 255, pattern = "^[A-Z\\sa-z]+$", minlength = 5, required = "required" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group ">
        Price
        <input name="price" class="form-control" maxlength=6 step="any" minlength=3 required />
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Image)
        <input name="postedfile" type="file" placeholder="Upload Image" accept="image/*" required @*class="form-control"*@ />
        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">

            <input type="submit" value="SUBMIT" class="btn btn-default" />&emsp;&emsp;

        </div>
    </div>
</div>


}



@section ViewSpecificJavascript
    {
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $(".alert").fadeOut(100, null);
            },
                3000);
        });

    </script>
}

KABE Food Ordering System/Views/Food/Index.cshtml
@{
    ViewBag.Title = "View Foods";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
@if (ViewBag.Message != null)
{
    if (ViewBag.Message == "Success")
    {
        <div class="alert alert-success">
            <p>@ViewBag.Message <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> </p>

        </div>

    }
    else if (ViewBag.Message == "Exist")
    {
        <div class="alert alert-error">
            <p>Branch Name Exist <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> </p>

        </div>

    }
    else if (ViewBag.Message == "Error")
    {
        <div class="alert alert-error">
            <p>@ViewBag.Message <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> </p>

        </div>

    }
}

@if (ViewBag.Results == null)
{
    <h4><strong>You have added any food yet</strong></h4>
}
else if (ViewBag.Results != null)
{
    <h3>Total Items: @ViewBag.TotalItems</h3>

    <table class="table">
        <tr>
            <th>&nbsp;</th>
            <th></th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.Results)
        {
            <tr>
                <td>
                    @{
                        var getImage = item.Image;
                        //var getImage = @item.SmallThumbnailjpg;
                    }
                    <img src="data:@item.ContentType;base64,@getImage" alt="@item.Name" style="width:120px; height:100px;" />
                </td>
                <td>
                    <h3> <strong>@item.Name</strong></h3>
                    
                </td>

                <td>
                    <h4>
                        <strong>
                            N @Math.Round(item.Price, 2).ToString("N2", System.Globalization.CultureInfo.InvariantCulture)
                        </strong>
                    </h4>
                    @*<button>

                        <a href=@Url.Action("New", new {foodId=item.Id, restaurant=item.RestaurantName, price=item.Price})>Change Price</a>

                    </button>*@
                </td>
            </tr>
        }


    </table>
}
@section ViewSpecificJavascript
    {
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $(".alert").fadeOut(100, null);
            },
                3000);
        });
        $("#customers").dataTable();

    </script>

}

KABE Food Ordering System/Views/Food/Recommend.cshtml
@model IEnumerable<KABE_Food_Ordering_System.Models.Food>

@{
    ViewBag.Title = "Recommended Food";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>
    @Html.ActionLink("Order Food", "New","Order")
</p>
<h3>
    The recommended food is <strong>@ViewBag.Food</strong>
</h3>
<p>
    <code>These are the list of restaurants where you can get this food</code>
    @foreach (var item in ViewBag.Restaurants)
    {
        <ul>
            <li>
                @item
            </li>
        </ul>
    }

</p>
@section ViewSpecificJavascript
    {
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $(".alert").fadeOut(100, null);
            },
                3000);
        });
        $("#customers").dataTable();

    </script>

}